package persistence
import("context";"database/sql";"encoding/json";"errors";"github.com/jahla2/Xentra/backend/control-plane/internal/domain")
type PostgresIntegrationRepository struct{db *sql.DB}
func NewPostgresIntegrationRepository(db *sql.DB)*PostgresIntegrationRepository{return &PostgresIntegrationRepository{db:db}}
func(r *PostgresIntegrationRepository)Save(ctx context.Context,item domain.RepositoryIntegration)error{_,err:=r.db.ExecContext(ctx,`INSERT INTO repository_integrations(id,environment_id,provider,owner_name,repo_name,credential_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(environment_id) DO UPDATE SET provider=EXCLUDED.provider,owner_name=EXCLUDED.owner_name,repo_name=EXCLUDED.repo_name,credential_id=EXCLUDED.credential_id`,item.ID,item.EnvironmentID,item.Provider,item.Owner,item.Repo,item.CredentialID);return err}
func(r *PostgresIntegrationRepository)FindByEnvironment(ctx context.Context,id string)(domain.RepositoryIntegration,error){var item domain.RepositoryIntegration;err:=r.db.QueryRowContext(ctx,`SELECT id,environment_id,provider,owner_name,repo_name,credential_id FROM repository_integrations WHERE environment_id=$1`,id).Scan(&item.ID,&item.EnvironmentID,&item.Provider,&item.Owner,&item.Repo,&item.CredentialID);if errors.Is(err,sql.ErrNoRows){return domain.RepositoryIntegration{},errors.New("repository integration not found")};return item,err}
type PostgresIncidentRepository struct{db *sql.DB}
func NewPostgresIncidentRepository(db *sql.DB)*PostgresIncidentRepository{return &PostgresIncidentRepository{db:db}}
func(r *PostgresIncidentRepository)Save(ctx context.Context,item domain.Incident)error{evidence,_:=json.Marshal(item.Evidence);timeline,_:=json.Marshal(item.Timeline);_,err:=r.db.ExecContext(ctx,`INSERT INTO incidents(id,environment_id,question,status,summary,root_cause,confidence,recommended_action,evidence,timeline,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,summary=EXCLUDED.summary,root_cause=EXCLUDED.root_cause,confidence=EXCLUDED.confidence,recommended_action=EXCLUDED.recommended_action,evidence=EXCLUDED.evidence,timeline=EXCLUDED.timeline`,item.ID,item.EnvironmentID,item.Question,item.Status,item.Summary,item.RootCause,item.Confidence,item.RecommendedAction,evidence,timeline,item.CreatedAt);return err}
func(r *PostgresIncidentRepository)Get(ctx context.Context,id string)(domain.Incident,error){var item domain.Incident;var evidence,timeline []byte;err:=r.db.QueryRowContext(ctx,`SELECT id,environment_id,question,status,summary,root_cause,confidence,recommended_action,evidence,timeline,created_at FROM incidents WHERE id=$1`,id).Scan(&item.ID,&item.EnvironmentID,&item.Question,&item.Status,&item.Summary,&item.RootCause,&item.Confidence,&item.RecommendedAction,&evidence,&timeline,&item.CreatedAt);if errors.Is(err,sql.ErrNoRows){return domain.Incident{},errors.New("incident not found")};if err!=nil{return domain.Incident{},err};_ = json.Unmarshal(evidence,&item.Evidence);_ = json.Unmarshal(timeline,&item.Timeline);return item,nil}
func(r *PostgresIncidentRepository)List(ctx context.Context)([]domain.Incident,error){rows,err:=r.db.QueryContext(ctx,`SELECT id,environment_id,question,status,summary,root_cause,confidence,recommended_action,evidence,timeline,created_at FROM incidents ORDER BY created_at DESC`);if err!=nil{return nil,err};defer rows.Close();items:=[]domain.Incident{};for rows.Next(){var item domain.Incident;var evidence,timeline []byte;if err:=rows.Scan(&item.ID,&item.EnvironmentID,&item.Question,&item.Status,&item.Summary,&item.RootCause,&item.Confidence,&item.RecommendedAction,&evidence,&timeline,&item.CreatedAt);err!=nil{return nil,err};_ = json.Unmarshal(evidence,&item.Evidence);_ = json.Unmarshal(timeline,&item.Timeline);items=append(items,item)};return items,rows.Err()}
