ALTER TABLE environments ADD COLUMN IF NOT EXISTS cpu TEXT NOT NULL DEFAULT '';
ALTER TABLE environments ADD COLUMN IF NOT EXISTS memory TEXT NOT NULL DEFAULT '';
ALTER TABLE environments ADD COLUMN IF NOT EXISTS disk TEXT NOT NULL DEFAULT '';
ALTER TABLE environments ADD COLUMN IF NOT EXISTS containers JSONB NOT NULL DEFAULT '[]'::jsonb;
